joaopedev/agendamento-cras-campos

src/components/SidebarHome.tsx
src/pages/loginPage.tsx

ajustes de UI feitos na Sidebar e na Box

Login page feita com formatação para CPF e data de nascimento

---

src/components/SidebarFuncionario.tsx
src/pages/homeFuncionario.tsx
src/routes/routes.tsx

Atualização de routes.tsx para acomodar nova rota para homeFuncionario

Criação da página de funcionário e Sidebar complementar

---

package-lock.json
package.json
src/App.tsx
src/components/UserContext.tsx
src/index.tsx
src/pages/homePage.tsx
src/pages/loginPage.tsx
src/routes/routes.tsx

só deus sabe

---

src/pages/loginFuncionario.tsx
src/pages/loginPage.tsx

*está jogando um erro mesmo com a formatação do CPF correta*

new login funcionario

---

public/index.html
src/components/FooterLogin.tsx
src/components/HamburgerMenu.tsx
src/pages/UserEdit.tsx

Adicionado analytics do google
Adicionada cor preta no input do celular para melhor xp dos funcionarios Removido divider não utilizado
Dashboard escondido do hamburger

Adicionado analytics do google

---

src/components/SelecionarDia.tsx
src/components/SelecionarDiaFuncionario.tsx
src/pages/homePage.tsx

Fix Select Homepage
Trocada cor do DatePicker de acordo com o tipo de usuário

Fix Select Homepage

---

src/components/SelecionarDia.tsx

Feature horário de marcação apenas entre 9:00 e 23:59. Entre 00:00 e 8:59, um cardo com a mensagem "Não temos vagas disponíveis, tente novamente mais tarde."

Feature horário de marcação

---

src/components/SelecionarDia.tsx

Remoção dos ultimos horários da chatuba e matadouro para acomodar horários de funcionamento dos CRAS

Remoção dos ultimos horários da chatuba e matadouro

---

src/components/HamburgerMenu.tsx

Consertado botão de inicio que estava escondido no menu hamburger

Consertado botão de inicio que estava escondido no menu hamburger

---

src/pages/UserEdit.tsx
src/pages/homePage.tsx

Select homepage transformado em search
Tamanho card user edit aumentado para acomodar nomes longos de bairros

Select homepage e tamanho card user edit

---

src/interface/User.ts

adicionado bairro saturnino braga

adicionado bairro saturnino braga

---

src/components/FooterLogin.tsx
src/pages/cadastroPage.tsx
src/pages/loginPage.tsx

Adicionado footer login versao mobile e desktop com TOS e politicas de privacidade Fix rota para TOS pagina de cadastro

Adicionado footer login

---

src/components/BairroCras.tsx

Atualizado matadouro erro de digitação e não estava designando nenhum cras

Atualizado matadouro erro de digitação

---

src/components/SelecionarDia.tsx

Desbloqueio de Date Picker para Funcionarios e ADM fazendo com que eles possam agendar usuários até 600 dias para frente

Desbloqueio de Date Picker para Funcionarios e ADM

---

src/components/CardShowAgendamento.tsx

Adicionada mensagem apenas para os cras codin, pq guarus e ceu

Adicionada mensagem apenas para os cras codin, pq guarus e ceu

---

src/pages/suporte.tsx
src/routes/routes.tsx

adicionada pagina de suporte em branco

adicionada pagina de suporte

---

src/components/SelecionarDia.tsx

Adicionado toast para feedback de dia ocupado

Adicionado toast para feedback de dia ocupado

---

src/components/SelecionarDia.tsx

revertido toast de agendar

---

src/components/SelecionarDia.tsx

Novos horários de atendimento juntamente com nova lógica para disponibilização de horários para o CRAS 6. Bloqueio de agendamentos feito a partir das 21:00

Novos horários de atendimento

---

src/components/SelecionarDia.tsx

Horario de 16:30 removido

---

src/components/SelecionarDia.tsx

horas ajustadas novamente temp

horas ajustadas novamente temp

---

src/components/CardShowAgendamento.tsx

Card show agendmento agora mostra horário de forma mais precisa com horas e minutos

Card show agendmento agora mostra horário de forma mais precisa

---

src/components/SelecionarDiaFuncionario.tsx

Atualizado botões de atendimento

Atualizado botões de atendimento

---

src/components/SelecionarDia.tsx

Selecionar Dia refatorado
Adicionado feature de agendamento só ser possível às sextas-feiras Adicionada mensagem em dias da semana que não são sexta-feira Adicionada logica para mostrar uma das 3 mensagens de acordo com a situação do usuario

Novo Selecionar Dia
